# SPDX-FileCopyrightText: 2025 The Open Source Project Template Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    # Configure commit messages to follow conventional commit format
    commit-message:
      prefix: "fix"
      include: "scope"
    # Configure the format of pull request branch names
    pull-request-branch-name:
      # Use hyphens as separators in branch names
      separator: "-"
    # Automatically add these labels to created pull requests
    labels:
      - "dependencies"
      - "actions"
      # Group definitions for related dependencies
    groups:
      # Group for version control system related dependencies
      actions-dependencies:
        patterns:
          - "*"
        # Only group minor and patch updates
        update-types:
          - "minor"
          - "patch"
    # Separate major updates from groups
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Limit the number of open pull requests Dependabot can have at one time
    open-pull-requests-limit: 4
