// SPDX-FileCopyrightText: 2023 Digg - Agency for Digital Government
//
// SPDX-License-Identifier: CC0-1.0
= The Open Source Release Checklist
:toc:
:revdate: {docdatetime}
:revnumber: 0.0.0

== About

It is easy to forget a few important tasks when releasing and improving an Open Source Project.
This checklist is here to help your project with suggestions.

Use this checklist in a practical way - as a discussion starter for the project, as a base for future improvements.

== Documentation

* Verify that the project fulfills the basic standard of Community
Health Files (CHANGELOG, CONTRIBUTING etc). +
  See link:.././README.md[README.md - Template Files Explanation Section] for
a basic list and further information
* Add any relevant, usage documentation, Software Architecture Descriptions regarding the project

== Workflows

* Discuss your GitHub-workflow - a brief summary and suggestion can be found in link:../CONTRIBUTING.adoc[CONTRIBUTING - Pull Request Lifecycle]

== Project Quality

* Verify there has been a code review of the project
* Discuss and implement the projects testing goals and ambitions

== Release and versioning

* Use semantic versioning and release tags

== Naming and trademarks check

* Ensure that the project name does not conflict with an existing
project or infringe on trademarks
** Do a general sanity search engine check of the proposed project name.
** Do a trademark search at
https://www.prv.se/sv/immaterialrattsexpert/varumarke/databaser/[PRV]
+
____
It might be ok to use a name that is reminiscent of an existing trademark, if the existing trademark is used for other services/areas and is not recognized as a known trademark.
____

== Legal and Licensing

* Ensure that the license of the project is not in conflict with third party licenses
* Declare the licenses for _other resources than code_ (images, text etc). https://reuse.software[REUSE] will help you describe these.

== Security

TO-DO
* For Security details regarding GitHub-usage or Contributor-specific security, see (Under-Construction: How we work on GitHub and link:../CONTRIBUTING.adoc[CONTRIBUTING]

== People & maintenance

* Ensure there is a maintenance and archival (if non maintained) plan
* Ensure that any maintaining team has gotten some education or experience regarding working Open Source
* Ensure that any maintaining team has a plan for handling community issues (responding to issues, reviewing and merging pull requests)
* Is there a need for a release plan? - if so, ensure that is clear how it should be announced and promoted
* Every project README MUST have a ``Maintainer''-header. Team, individual, role, does not matter. If there are no Maintainers to be found, the project should be Archived.
** Additionally, the project SHOULD use a CODEOWNERS-file. 
  A CODEOWNERS-file can be more granualar in describing the project maintenance, whereas the README’s Maintainer-line might be more general.

== Open Source Excellence

There a quite a few extra steps you might want to consider for keeping your Open Source Projects clean, clear, re-usable, accessible and up-to-date.

* Consider https://reuse.software/[following the REUSE licensing standard]
* Prefer declaring licenses with the https://spdx.github.io/spdx-spec/v2.3/using-SPDX-short-identifiers-in-source-files/[SPDX-standard]
* Consider following the https://standard.publiccode.net/[criterias from Foundation for Public Code]
